### PR TITLE
[Xam/Info] - Fix XamGetLanguage & XGetLanguage Implementation

### PR DESCRIPTION
**Pull request by The-Little-Wolf**
Language values that is returned must match Xlanguage values. It seems xgetlanguage can't return values above 9 and will default to japanese, korean, or english depending on game region.

### CODE REVIEW

**Comment by The-Little-Wolf** [comment]
Screenshot 2024-11-30 114837

**Comment by The-Little-Wolf** [comment]
Screenshot 2024-11-30 115252

**Comment by OmarJTAG-RGH** [comment]
excuse me i need help

**Comment by Margen67** [comment]
@OmarJTAG-RGH Tech support belongs on the Xenia Discord server: https://discord.gg/Q9mxZf9

**Pull request merged**
