### PR TITLE
Remove beep

### PR DESCRIPTION
**Pull request by illusionyy**

### CODE REVIEW

**Comment by ghost** [comment]
You guys need to fork the third party repos on my account and repoint the submodules; i'm deleting this account.

**Comment by ghost** [comment]
please acknowledge this message!

**Comment by illusionyy** [comment]
Oi I'm forking rn

**Comment by Spaceghost** [comment]
Ah so it’s you two who are playing games huh? Fascinating you’re publicly being seen doing this to people. This will be hilarious

**Comment by illusionyy** [comment]
I had no involvement until the two PRs to clean up the mess caused by #180

**Comment by ghost** [comment]
> Ah so it’s you two who are playing games huh? Fascinating you’re publicly being seen doing this to people. This will be hilarious

Illusion was not involved in the beep/message PR at all, just me

**Comment by alex-p30** [comment]
> You guys need to fork the third party repos on my account and repoint the submodules; i'm deleting this account.

Bit of an overreaction, no? Just step away from the computer for a bit, take a nap maybe.

**Comment by Spaceghost** [comment]
Thank you both for being very honest with me about this. I appreciate the handling @illusion0001 and apologize for insinuating you handled merging or authoring.

@chrisps thank you also for being upstanding about responding to your mistake here. I won't not say it wasn't what it was but since you're here and taking the response with all due humility I'll suspend all judgment. This wasn't the kind of code that belongs outside of repositories you're not an admin owner of, and I think you'll never forget that now. You'll also never write code that harms users, a portion of which are disabled. If it weren't for the _harmful_ level of the sound, which you as an engineer should have been innately curious about and looked up by compulsion, this would have been a nagscreen no one would have batted an eye with any serious contempt.

These things are a costly lesson, a burden paid by us the trusting members of the emulation community. I've been a part of it since the 90's. I hope you understand and start out fresh again. I'd be so mad at myself if I ruined a good identity. You have my respect for shielding the remaining canary team here from the fallout.

~Spaceghost

**Pull request merged**
