### PR TITLE
[WIP] Linux port fixes

### PR DESCRIPTION
**Pull request by RodoMa92**
I've tried to merge as much linux improvements into this PR in the hope to be able to finally bring support to linux platforms. I've tried to minimize as much as I could on changes for Windows, but this should really be tested.

Current state:
* It compiles fine
* The ui opens fine
* Thanks to old unmerged commits the file picker now works fine on linux
* Loading stuff under Linux it still partially broken, but I haven't tested enough stuff on it to know how much stuff is left to do.

### CODE REVIEW

**Comment by Gliniak** [comment]
Cool, but I have few issues with it.

1. It would be easier if you could first make PR to master with working unix build (by that I mean running games not compilation itself) as it also fails there and after that PR it to canary with changes that must be made to canary.
3. It's mess in commits right now. Squash all changes to one commit, because all these merge commits looks bad.

**Comment by RodoMa92** [comment]
> Cool, but I have few issues with it.
> 
>     1. It would be easier if you could first make PR to master with working unix build (by that I mean running games not compilation itself) as it also fails there and after that PR it to canary with changes that must be made to canary.
I already had a Linux build of the stable release on github fixed, but since this is a fork of the original stable emulator I couldn't fork it again (thanks github, I guess), so I had to temporary delete the old fork from my account. I still have the repo locally, so it's should not really be a problem to do it, but I'll probably need to delete the canary fork again. LMK which approach you prefer beetween the two.
>     2. It's mess in commits right now. Squash all changes to one commit, because all these merge commits looks bad.
Yeah, I know, that's why I flagged it as a draft. If this is fine, I can rebase and squash commits no problem.

Marco.

**Comment by Shoegzer** [comment]
I'm confused, why did you close this?  This would have been a fantastic contribution and likely a decent step forward towards a working Linux build.  Hoping this is due to work in progress with the fork as you mentioned above.

**Comment by RodoMa92** [comment]
Yeah, I'll come back with this code chunking it better and starting with xenia stable first, don't worry.

Haven't had the time yet, but it's coming. I'll fork xenia stable from someone who has a separated fork (github is dumb) and begin from there.

Marco.

**Comment by Shoegzer** [comment]
What a relief to know, for me and many others I'm sure. And yeah, github can be a challenge sometimes. Thanks!

**Comment by cyberwolfie1** [comment]
Any news on this?

**Comment by RodoMa92** [comment]
Haven't had the time yet, but a lot of my changes do already have a PR open from other people on stable last time I took a look at it. Not sure if they have already landed or what, I might take a look soon, thanks for reminding me though.

**Comment by RodoMa92** [comment]
Yeah, they are still there opened with not a lot of feedback from the team, see [here](https://github.com/xenia-project/xenia/pulls?q=is%3Aopen+is%3Apr+label%3Aplatform-linux). That's why I mainly lost interest in pushing them upstream if I remember correctly. If I would see some movement in them (as merging) I would try to push it further.

**Comment by cyberwolfie1** [comment]
> Yeah, they are still there opened with not a lot of feedback from the team, see [here](https://github.com/xenia-project/xenia/pulls?q=is%3Aopen+is%3Apr+label%3Aplatform-linux). That's why I mainly lost interest in pushing them upstream if I remember correctly. If I would see some movement in them (as merging) I would try to push it further.

Ah, I see - I would be very interested in seeing this work natively on Linux, but I unfortunately do not have the required dev experience to help directly. Is there anything that I could do to help this along?

**Comment by RodoMa92** [comment]
> > Yeah, they are still there opened with not a lot of feedback from the team, see [here](https://github.com/xenia-project/xenia/pulls?q=is%3Aopen+is%3Apr+label%3Aplatform-linux). That's why I mainly lost interest in pushing them upstream if I remember correctly. If I would see some movement in them (as merging) I would try to push it further.
> 
> Ah, I see - I would be very interested in seeing this work natively on Linux, but I unfortunately do not have the required dev experience to help directly. Is there anything that I could do to help this along?

Hard to say, TBH. If the main team do not actively engage with them with feedback/testing, they will probably remain there stuck forever and often require rebase on top of the latest changes, which further discourage additional work if they are still left there to rot again. Sadly this is not that uncommon in open source voluntair work. I would be happy to have a working port of Xenia to use natively on Linux, but it doesn't really seem to be the main focus for now as far as engagement goes.

**Comment by Gliniak** [comment]
Feel free to push them to canary in some smaller batches. I had some hope back then that maybe (to master) it will be possible to merge it but not anymore.
For sure there will be a lot more to do on canary to make it work, but at least you can be sure that it will be merged and developed

**Comment by RodoMa92** [comment]
> Feel free to push them to canary in some smaller batches. I had some hope back then that maybe (to master) it will be possible to merge it but not anymore. For sure there will be a lot more to do on canary to make it work, but at least you can be sure that it will be merged and developed

If you confirm that on here they will progress it further I can take a look at porting the changes stuck on stable on here. Does canary have different devs compared to stable?

**Comment by Gliniak** [comment]
They for sure, but please do them in smaller batches so they're easier to understand. 
Mostly me, but few other have ability to merge PRs

**Pull request closed without merging**
