### PR TITLE
Update discord_presence.cc

### PR DESCRIPTION
**Pull request by Auxy6858**
Fixed xenia's discord rpc not loading the xenia logo.

### CODE REVIEW

**Comment by Auxy6858** [comment]
If maintainers don't want to use my app ID, you could do it yourself through the discord developer portal.

**Comment by Gliniak** [comment]
But I updated it last year and I can see it still kinda works.
image

**Comment by Auxy6858** [comment]
I fixed the logo
Screenshot 2024-07-13 192344

**Comment by Gliniak** [comment]
That's why I wrote kinda. I uploaded correct image last year, but it never applied it for whatever reason. I can try again

**Comment by Gliniak** [comment]
Thanks for reminding me about that. Fixed with actual id

**Pull request closed without merging**
