### PR TITLE
[3PP] Updated: half, xbyak, sdl2

### PR DESCRIPTION
**Pull request by Xphalnos**
- The version of **half** is from 2013, I think a facelift in 2017 won't hurt.
- I updated **xbyak** because it received many updates with support for **AVX10.2** processors.
- **SDL2** was updated because it fixes many bugs.
- Tested on **Grand Theft Auto IV**, **Minecraft** and **Need For Speed ​​Most Wanted 2005**.

| Librabry | Old | New |
| ------------- | ----- | ------- |
| half | 1.11.0 | 1.12.0 |
| xbyak | 7.07.1 | 7.20 |
| SDL2 | 2.30.0 | 2.30.8 |

### CODE REVIEW

**Comment by Xphalnos** [comment]
@Gliniak, is this commit interesting?

**Comment by Gliniak** [comment]
You can change commit message: ``[3PP] Updated: half, xbyak, sdl2``

After that I have nothing against it, but be patient next time.

**Comment by Xphalnos** [comment]
> You can change commit message: `[3PP] Updated: half, xbyak, sdl2`
> 
> After that I have nothing against it, but be patient next time.

Excuse me for my impatience, it's true that I have some faults to correct ;)

**Comment by Xphalnos** [comment]
> You can change commit message: `[3PP] Updated: half, xbyak, sdl2`
> 
> After that I have nothing against it, but be patient next time.

Excuse me for my impatience, it's true that I have some faults to correct ;)

**Comment by Gliniak** [comment]
I clicked it too fast and merged it...

I wanted you to change commit message not PR message. I will change it manually

**Pull request merged**
