### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Juanjosevilla2**
Hello! Here I leave you a security policy, what do you think for the xenia canary emulator, okay?  :D

### CODE REVIEW

**Comment by Margen67** [comment]
This isn't even English..

**Comment by illusionyy** [comment]
copy paste from xbox, ms pages.

**Comment by Juanjosevilla2** [comment]
> esto ni siquiera es ingles..

Sorry, I'm going to try again, I'm confused :(

**Comment by Margen67** [comment]
> > esto ni siquiera es ingles..
> 
> Sorry, I'm going to try again, I'm confused :(

We don't need this. If you spam this repository with pull requests we will block you.

**Comment by Margen67** [comment]
#39

**Pull request closed without merging**
