### PR TITLE
[XAM] - XGetAVPack Enhancements.

### PR DESCRIPTION
**Pull request by James-Coding**
After some research I was able to find the correct values of AVPack, and this is a quick fix for them. The High Definition settings read and set the resolution using a 2 bytes long setting in XConfig, but since this is currently unimplemented it will not work as intended in apps like the dashboard, who indeed read screen resolution, altough the games will work perfectly.

### CODE REVIEW

**Comment by randprint** [comment]
Looks cool, thanks for making the PR, can you tell us how you got the labels for all of them?

**Comment by illusion98** [comment]
Nitpick. Rename commit message.

**Comment by illusion98** [comment]
What happened to https://github.com/xenia-canary/xenia-canary/pull/3 btw?

**Comment by Margen67** [comment]
@James-Coding Can you rebase this?

**Comment by illusion0001** [comment]
Soon™

**Comment by James-Coding** [comment]
> Looks cool, thanks for making the PR, can you tell us how you got the labels for all of them?

Yes, I was investigating a way to implement full XConfig on xenia, and I discovered that there where some settings that actually read and write screen resolution, but something was wrong, so I looked at AVPack and started to check against the dashboard labels, there is where I got the labels from, and sorry for the laaaaaate reply, my internet was gone...

**Comment by James-Coding** [comment]
And sorry bout #3, kinda new to Git

**Pull request closed without merging**
