### PR TITLE
…

### PR DESCRIPTION
**Pull request by ghost**
Implement RtlRandom (which despite its name is located in Xam, not xboxkrnl, which is why its not in xboxkrnl_rtl)

Stub XamVoiceSubmitPacket
Stubs for __CAP_Start_Profiling/End_Profiling/Enter_Function/Exit_Function 

add a note about io_status_block in NtDeviceIoControlFile, change the param's type 

move the X_IOCTL_ constants from NtDeviceIoControlFile's body into xbox.h 
add X_STATUS_INVALID_IMAGE_FORMAT to xbox.h
Implement XexLoadImageHeaders
Much more correct version of IoCreateDevice, properly initializes/allocates device extension data 
Stub version of IoDeleteDevice

Open the quickstart guide in the browser the first time a user opens the emulator

Add some persistent flags that are stored in the registry on windows, not in the config. These are just used to indicate whether one-time tasks have run, like showing the quickstart guide. On non-windows platforms a default value is returned that skips any of these tasks so they don't run every single time.

If the user opens a .iso file, show a warning telling them that we do not condone or support piracy. If the user closes the messagebox within two seconds set a sticky flag that will show them the warning every time instead. Otherwise the warning is never shown again. The Beep function is used to spook them a bit, to hopefully make them less likely to skip the message 

If a user opens an archive file, which we do not support, explain to them that they're dumb.

Removed messages intended to "catch" pirates.  If they're out there, we don't want to know about them. A huge chunk of the discourse on our discord is now about piracy. Hopefully these changes will deter them from coming to us for now, but some of these changes may backfire and need reverting

### CODE REVIEW

**Comment by Cheezy096** [comment]
This has already been merged however it does not seem right to me that you should bother the user about piracy and increase this bothering if the user closes the piracy messagebox very quickly. Who are you to say whether the user is allowed to run a legal copy or not on your open source emulator? Piracy is bad but you really shouldn't be an obnoxious bitch about it. This is an emulator, not a homebrew app for a modded xbox 360 during the times this console was still the latest model.

* You should not care how legal the copy of the game the user is playing is, you should only care on whether the emulator is doing it's job correctly in playing those games
* Perhaps piracy is the users only way to get these games?
* You are caring about piracy for a console released 18 years ago

**Comment by ghost** [comment]
> This has already been merged however it does not seem right to me that you should bother the user about piracy and increase this bothering if the user closes the piracy messagebox very quickly. Who are you to say whether the user is allowed to run a legal copy or not on your open source emulator? Piracy is bad but you really shouldn't be an obnoxious bitch about it. This is an emulator, not a homebrew app for a modded xbox 360 during the times this console was still the latest model.
> 
> * You should not care how legal the copy of the game the user is playing is, you should only care on whether the emulator is doing it's job correctly in playing those games
> * Perhaps piracy is the users only way to get these games?
> * You are caring about piracy for a console released 18 years ago

Piracy doesn't bother me, the emulator still plays the games, and they can disable the repeating messagebox by hitting Ctrl-F2. The point is to make an impression so that if the user comes to our Discord they know not to incriminate themselves, it actually is to their benefit. Users come into our Discord, incriminate themselves, anti-piracy users pile on them and it becomes this whole shitspectacle that drowns out any real discussion of the emulator itself. You've really not read the PR closely enough if you think this is about punishing pirates.

**Comment by Cheezy096** [comment]
> Piracy doesn't bother me, the emulator still plays the games, and they can disable the repeating messagebox by hitting Ctrl-F2. The point is to make an impression so that if the user comes to our Discord they know not to incriminate themselves, it actually is to their benefit. Users come into our Discord, incriminate themselves, anti-piracy users pile on them and it becomes this whole shitspectacle that drowns out any real discussion of the emulator itself. You've really not read the PR closely enough if you think this is about punishing pirates.

Entirely my bad, should've read the PR more closely as you said. Read the messagebox section and went auto retard mode due to the amount of people I see that cry about piracy being a horrible crime (no matter the situation) but no, I should've actually put thought into it instead of being retarded and sending that, sorry.

**Comment by ehw** [comment]
...is the beeping really necessary? It almost blew my ear drums out.

**Comment by ghost** [comment]
> ...is the beeping really necessary? It almost blew my ear drums out.

I'd be open to lowering its pitch

**Comment by Faz8** [comment]
>have iso support
>gives incredibly loud beep if any iso is opened

how pathetic, maybe you should open up to getting some friends

**Comment by Timo654** [comment]
why not just completely remove ISO support then, if it's only used by pirates?

**Comment by ghost** [comment]
incredibly petty and for no reason

**Comment by ghost** [comment]
> why not just completely remove ISO support then, if it's only used by pirates?


It is not only used by pirates. Some users convert their games to ISO, either because the games only work as ISO (I'm not sure how many games require this, I imagine few but have no real data) or because they were misled into thinking they had to in order to play their games.

But also, removing ISO support would just mean people would maintain another fork that still has support for ISO, or people would cling to older versions of Xenia. 

Anyway, preventing people from using ISO's or punishing pirates wasn't the goal. I outlined why these changes were made in this message: https://github.com/xenia-canary/xenia-canary/pull/180#issuecomment-1646951867

**Comment by Timo654** [comment]
> It is not only used by pirates. Some users convert their games to ISO, either because the games only work as ISO (I'm not sure how many games require this, I imagine few but have no real data) or because they were misled into thinking they had to in order to play their games.

so basically anyone who plays a game that has to be in ISO format will automatically be flagged a pirate and will be earraped whenever they want to play their game? even more if they click the button faster than the hidden timer?

i can understand a warning message,though it is weird to also blame people who dumped their games legit, I've seen other emulators detect pirates based on filepath instead, cause your average pirate won't move the files outside "game-piracy-site.com" folder. The beeping seems unnecessary though, and it's very loud. 

> But also, removing ISO support would just mean people would maintain another fork that still has support for ISO, or people would cling to older versions of Xenia.

and earraping ISO users won't?

**Comment by DniweTamp** [comment]
why not just make a message box with a 5 second timer before ok button becomes clickable instead of damaging users' ears

**Comment by alexalc02** [comment]
Why not just have a disclaimer show up the first time xenia is run instead of when you load an ISO?
have it be a window that you can only close after a fixed amount of time has passed (maybe 10 seconds)

should filter out most pirates from seeking support in the discord or at least they will make sure to not reveal where they got the game from

**Comment by MiniGrief** [comment]
While I imagine people coming into the Discord to ask for help with their pirated games is annoying, this feels like throwing a sledgehammer at the problem which is going to cause a lot of collateral damage. Lessening the beep was a step in the right direction, but it's seriously not enough to do what you're trying to do.

People will make forks to remove this and they will still go into the Discord with or without a message to say otherwise. I also have a personal problem with it due to being autisitic and loud unexpected noises are extremely distressing. It could be argued that the beep is ableist due to issues like that.

I also would like to point out the irony that by trying to detour an illegal practice (or at least distance yourselves from it), you now resemble one in the form of scam websites which pop up warnings about something like your PC being hacked while blasting loud beeps.

**Comment by ghost** [comment]
Okay, the Beep has been removed! Sorry everyone, did not realize it was so bad, and thanks for your feedback

**Comment by acanthii** [comment]
I still think the message itself is overkill in its current state. You yourself said you won't remove iso support because people often convert their games to iso format legitimately.

Instead of treating every .iso user as a criminal, maybe do what yuzu/rpcs3 does and display a message upon first boot saying you don't support piracy, and if you're found to have pirated copies of games, you won't have support on the discord server. (And make them click a checkbox to make sure they read it)
This informs the user, and doesn't nag them for playing games in a certain format. 

The earrape was well intentioned but probably wasn't thought about for more than the moment of its initial inception, and made this entire dev team look bad for allowing it to even merge.
From an outsiders perspective, it looks like the ambiguous name of this PR was meant to fly under the radar. In the future, I'd give PR more transparent names like "anti-piracy measure" and give it more time before merging to evaluate community feedback.

**Comment by ds8k** [comment]
This is absolutely wild and should've never been merged in.

**Comment by mahougomi** [comment]
> ...and made this entire dev team look bad for allowing it to even merge. From an outsiders perspective, it looks like the ambiguous name of this PR was meant to fly under the radar. 

I agree. I found out about this via Twitter, and from the outside looking in it looks like this has been added to the master branch. As well, my assumption was that someone else would have to approve a pull request for something like this. Neither are true.

For the reasons many have stated above, I think this was a bad PR. It appears to me that chrisps actually did bundle the anti-piracy stuff in with important code, which would have obfuscated something like this. Removing the beep is obviously a good change but it's a ridiculous violation of user trust for it to even be implemented that way at all. Not a fan of accusing users of being stupid, even if that is limited to comments in the code.

**Comment by SneakySnake04** [comment]
> Okay, the Beep has been removed! Sorry everyone, did not realize it was so bad, and thanks for your feedback

What about the ISO warning? why won't you remove that? i have legitimate backups in ISO format, and i know i can just CTRL+F2, but you say nothing about that anywhere

**Comment by DarthShader** [comment]
Who the hell thought this was a good idea? You certainly weren't even confident in your own skullduggery @chrisps 
" spook them a bit"
"they're dumb"
"these changes may backfire and need reverting"

This behavior is beyond childish, embarrassing, and detrimental to the Xenia project's public image.

**Comment by JPeisach** [comment]
I dont want to fan the flames, but I'll politely say that this isn't the way to go about it. ISOs have always been the standard format, and even going out of the way to bypass a user audio bypass is cruel.

What do you expect the modding community to do? Change the format of game dumps to something else?

Xenia is an *emulator*, not another software where you guys can make your own versions of those anti piracy screens on YouTube.

The way I feel you guys handled this was whack, but I hope you guys find a solution to pirates still looking for help in your discord, despite rules being clearly layed out

Also: still haven't the message like "terminated due to lack of basic computer skills" is still immature and petty. I'm sorry but, it takes away from the confidence of the emulator devs I have, and not that I've used Xenia that much, a project like this is not something I would use nor want to support.

**Comment by BillieBlueberry** [comment]
this was already removed so shhhhh be quiet

**Comment by 3doplayer67484** [comment]
> I dont want to fan the flames, but I'll politely say that this isn't the way to go about it. ISOs have always been the standard format, and even going out of the way to bypass a user audio bypass is cruel.
> 
> What do you expect the modding community to do? Change the format of game dumps to something else?
> 
> Xenia is an _emulator_, not another software where you guys can make your own versions of those anti piracy screens on YouTube.
> 
> The way I feel you guys handled this was whack, but I hope you guys find a solution to pirates still looking for help in your discord, despite rules being clearly layed out

Simple just don't have a discord lmao
Problem solved in like 2 nanoseconds

**Comment by acanthii** [comment]
> this was already removed so shhhhh be quiet

The beep was removed, the iso nagging wasn't

**Comment by alexalc02** [comment]
fully reverted in the latest commit but it seems like the non-antipiracy changes were reverted too

**Comment by AceSevenFive** [comment]
The tone of the nag message and creating a moron flag for ""skipping"" it gives off "Our cleanroom RE involves reading Microsoft documentation and imbibing their propaganda on how piracy is the devil" vibes

**Comment by windwakr** [comment]
This is just straight up malicious.

**Comment by BillieBlueberry** [comment]
and it's already been removed after the dev realized their mistake.

**Comment by Dacatzgoescodin5267** [comment]
Go fuck yourself @chrisps You dick bag!

**Comment by prism2001** [comment]
> and it's already been removed after the dev realized their mistake.

i disagree. seems more like he just removed it because he got caught. as others have mentioned, the title of the PR as well as blending it in with legitimate changes and not even mentioning the loudness of the beep anywhere in the initial post strongly gives off the impression that this was done intentionally and was meant to be inconspicuous

this PR getting accepted reflects very poorly on xenia even if the end goal was to deter piracy (but let's be honest, do you really think the vast majority of people using emulators *aren't* getting their games from piracy sites? lmfao)

and i think going forward chrisps's PRs should be more closely inspected (assuming he doesn't get blacklisted from contributing further) in case anything similar is attempted in the future

**Comment by UIScript** [comment]
> > and it's already been removed after the dev realized their mistake.
> 
> i disagree. seems more like he just removed it because he got caught. as others have mentioned, the title of the PR as well as blending it in with legitimate changes and not even mentioning the loudness of the beep anywhere in the initial post strongly gives off the impression that this was done intentionally and was meant to be inconspicuous
> 
> this PR getting accepted reflects very poorly on xenia even if the end goal was to deter piracy (but let's be honest, do you really think the vast majority of people using emulators _aren't_ getting their games from piracy sites? lmfao)
> 
> and i think going forward chrisps's PRs should be more closely inspected (assuming he doesn't get blacklisted from contributing further) in case anything similar is attempted in the future

Absolutely. This was just a disaster.

**Comment by chowder908** [comment]
You can be anti piracy without being a braindead dipshit basically turning the emulator into a virus with malicious code...

**Comment by ryzendew** [comment]
@chrisps don't make PR's anymore you ended up given xenia a bad name and made it a joke to alot of people and now they have to revert your garbage. bad form ...

**Comment by ghost** [comment]
Let this controversy serve as an example for other emulator devs on what _not_ to add to an emulator. Especially one that will be used primarily by people without the original hardware

**Comment by aaaaaa123456789** [comment]
I'm just another random passerby brought here by the controversy... but I'm not sure of why people are saying this was already removed/reverted? I can still see the code in the branch. (Screenshots because links to the branch will hopefully be outdated soon enough.)

Here's the message belittling users and sending them to a Google search:
image

And here's the infamous warning and the "moron flag" which "assumes the user is an idiot":
image

Am I missing something here?

**Comment by acanthii** [comment]
> I'm just another random passerby brought here by the controversy... but I'm not sure of why people are saying this was already removed/reverted? I can still see the code in the branch. (Screenshots because links to the branch will hopefully be outdated soon enough.)
> 
> Here's the message belittling users and sending them to a Google search: image
> 
> And here's the infamous warning and the "moron flag" which "assumes the user is an idiot": image
> 
> Am I missing something here?

No, only the beeping code was removed. The ISO nagging that calls the user an idiot is still there.

**Comment by theo77186** [comment]
The rest of the revert is in #185 (to be merged).
The whole anti-piracy fiasco is, in my opinion, terribly executed if not outright malicious. I get the intent behind this, but this isn't how it should be done.

**Comment by prism2001** [comment]
> The rest of the revert is in https://github.com/xenia-canary/xenia-canary/pull/185 (to be merged).
The whole anti-piracy fiasco is, in my opinion, terribly executed if not outright malicious. I get the intent behind this, but this isn't how it should be done.

agreed. if they wanted to add an anti-piracy message, doing it the same way numerous other emulators do it would've been fine. that is, having a message that displays *once* upon first boot that says something like this:
"Xenia is not intended to be used for piracy. We will not provide technical support for anyone using a pirated copy of a game."

**Comment by ghost** [comment]
> "Xenia is not intended to be used for piracy. We will not provide technical support for anyone using a pirated copy of a game."

This is exactly what other emulators (Dolphin, RPCS3, etc.) have been doing for over a decade and it gets the point across perfectly. I'm not sure what gave the Xenia people the idea that calling the user stupid and blowing their eardrums out because of a file format would ever be okay. It only gives the Xenia project a bad name and encourages people to use RPCS3 for their Red Dead fix instead.

**Comment by prism2001** [comment]
additionally, punishing people for loading an iso or any other type of archive doesn't solve the issue of piracy, either. all the user would have to do is just extract the .xex file out of the archive and then load that to bypass the message. it won't magically change the fact that the user may _(or may not)_ have acquired the game through illegal channels.

all you're doing in this case is making the emulator annoying (and potentially dangerous) to use, and *also* inadvertently punishing anyone who is using a personal rip that happens to be packed up into an ISO/RAR/etc

**Comment by GeorgeGedox** [comment]
Wow, nice way of making sure people move to a fork of this that actually cares about the community. I won't be using or recommending this emulator to anyone after such a damaging move.

**Comment by gilesfun** [comment]
holy shit this was a terrible idea not only does this damage xenia's reputation but also the user's hearing? 

an absolute liability 

i recommend that discord drama is kept to the discord servers

**Comment by coreln** [comment]
I'm in no way advocating for software piracy as it's immoral and illegal but can't pirates just easily bypass this "anti-piracy" measure by pirating a non .iso rip of a proprietary game? Seems pretty ineffective as a means of stopping piracy.

**Comment by plrusek** [comment]
> Okay, the Beep has been removed! Sorry everyone, did not realize it was so bad, and thanks for your feedback

what a crock of shit. "did not realize it was so bad"? the comments you left around the code tell a completely different story. you knew exactly what you were doing. for how smart it takes to be an emulator developer, you sure are thick skulled to even think people would accept this. holy snap.

**Comment by Kimarnic** [comment]
Why are the most brilliant people always the most insane, Jesus Christ.

**Comment by twist84** [comment]
Jesus was insane indeed.

> Why are the most brilliant people always the most insane, Jesus Christ.

**Comment by lppedd** [comment]
I don't understand the whole purpose of the disclaimer, just put it on the website's download page and you're done.

Discord is accessible by everyone, so if you want more control over it, just don't use it and move to something else. Support discussions can be moved to GitHub's Discussions now.

The comments and code you wrote shows the kind of person you are, just remember this going forward.
Take some time off open source.

**Comment by JPeisach** [comment]
> Jesus was insane indeed.
> 
> 
> 
> > Why are the most brilliant people always the most insane, Jesus Christ.
> 
> 
> 
> 

Yeah, Jesus has probably died if he tried coming back.

**Comment by alex-p30** [comment]
> > This has already been merged however it does not seem right to me that you should bother the user about piracy and increase this bothering if the user closes the piracy messagebox very quickly. Who are you to say whether the user is allowed to run a legal copy or not on your open source emulator? Piracy is bad but you really shouldn't be an obnoxious bitch about it. This is an emulator, not a homebrew app for a modded xbox 360 during the times this console was still the latest model.
> > 
> > * You should not care how legal the copy of the game the user is playing is, you should only care on whether the emulator is doing it's job correctly in playing those games
> > * Perhaps piracy is the users only way to get these games?
> > * You are caring about piracy for a console released 18 years ago
> 
> Piracy doesn't bother me, the emulator still plays the games, and they can disable the repeating messagebox by hitting Ctrl-F2. The point is to make an impression so that if the user comes to our Discord they know not to incriminate themselves, it actually is to their benefit. Users come into our Discord, incriminate themselves, anti-piracy users pile on them and it becomes this whole shitspectacle that drowns out any real discussion of the emulator itself. You've really not read the PR closely enough if you think this is about punishing pirates.

This is why you have no friends.

**Comment by Quackdoc** [comment]
This was bordering on malware, punishing people for using ISOs which has been the defacto standard in game preservation for ages. absolutely baffled how anyone thought this was a good idea, Shame on the dev who wrote the code, essentially mocking ISO as a format for pirates despite it being commonly used for preservation and comparing your dumped ISO's against redump is how you can verify you have a good dump.

shame.

**Comment by slickJ17** [comment]
@chrisps you need to be brutally killed and your remains eaten by vultures faggot

**Comment by xan1242** [comment]
As others have pointed out - actions like this will make users lose trust in Xenia developers. Especially at the individual who wrote the code. (Seriously, did he not think that anyone could use `git blame` to figure out who wrote that?)

If this is to happen enough times, people _will_ fork the project and get the motivation to maintain it. Especially considering its popularity.

Incredibly petty all around, especially with all the attempts to hide it. Keep Discord drama to Discord, a good chunk of Xenia users aren't even in there to begin with.

**Comment by BrodyGaming420** [comment]
really takes some public shaming to completely remove this huh, it's dumb that this happened in the first place, i would reccomend for the devs to atleast do a quick check in the PRs for canary as well to avoid this from happening, i love Xenia and seeing the image of the rest of the devs be tainted because of a single malicious PR from a dumbass sucks

**Comment by foxt** [comment]
<details>
<summary>This was originally longer</summary>
Just as if you was a guest in someone's house, treat the user with respect, Your application is a guest on the users machine. Always think: if i was in a bad mood, would this piss me off?

- Code should never attempt to fright the user
- Code should never bypass users explicit rules (don't play audio if the volume is turned off) A user made a choice for a reason. Loud audio can burst speakers, cause fires, cause hearing loss. The users audio device might even be a medical device (I have actually seen this before) where playing audio can cause physical harm.
- Code shouldn't assume bad intention (don't assume everyone using an .iso is a pirate)
- Code shouldn't touch anything outside of its domain (some users classify opening a web browser without clicking a link as this, another example is if a game mod made all the text upside down in the game on April Fools)
- Never ever ever **EVER** punish the user by doing anything more than a lockout. Even if you have very high confidence the user is doing something bad, that is not your decision to make. You do not know the intention of the user.

If in doubt, always run on the side of caution. If you know something might backfire, just don't do it unless you have **very** good reason.
</details>

After reading the response, I feel it's more important to just say: respect the user. Don't accuse them of anything without being 100% sure. Don't be petty and punish the user (annoy them even more because you don't believe they read your error message enough). Don't insult the user, no matter how stupid they might be (I know). Some people might miss something. Treat the user as if you was a guest in their house. 

Also, even if an application violates these boundaries. Be civil. Stop harrassing @chrisps or anyone else for that matter. We have all made mistakes.

**Comment by aaaaaa123456789** [comment]
To add to @foxt's excellent post, the very definition of malware is software that does something the user doesn't want to do.

**Comment by ghost** [comment]
There are too many comments to respond to here:



People are saying the sound was forced to max volume, that is not true, and the comment is being misinterpreted. When it talks about windows sounds being disabled it is not saying it bypasses the users volume setting, it is talking about this:
image

^That is what I meant when talking about windows sounds. They're the sounds that are made when you open a folder or a messagebox pops up. MessageBeep did not work when I tested it but Beep did, so I figured the reason why was because I have windows sounds disabled. I've retested the old build, another user on the discord did as well, it does NOT play at max volume and uses your volume settings instead.


The screenshot of the google search for how to open a zip file + the messagebox is taken out of context, although yeah the message is rude. Users often came in to the discord unable to play their games because they were in zip files and the user hadn't unzipped them. Instead of a message that told them nothing I made it open a browser window "how to extract a (insert archive file here)". The message is shown after opening a browser window. The code does not happen in response to you googling things

**Comment by ghost** [comment]
I apologize that some of the variable names are rude, and that the message is poorly worded, and I have apologized for the Beep. I am no longer a part of the Xenia Canary or Xenia team, please stop raiding their discord and threatening people. I authored and merged this PR, literally nobody else had any involvement.

**Comment by NekomimiNebula** [comment]
Can this PR get reverted so if the author has now left the team?

**Comment by lppedd** [comment]
@NekomimiNebula this is already reverted (partially, soon completely).
Someone please lock this thread now that the story came to an end, or this repo's gonna be featured on github-drama.

**Comment by foxt** [comment]
> Can this PR get reverted so if the author has now left the team?

AFAIK, that is being worked on.

Honestly, reading the response from the author which puts it incredibly context, there is a massive over reaction. We all make dumb shit, but there's no need for actual harassment.

**Comment by CookiePLMonster** [comment]
> Honestly, reading the response from the author which puts it incredibly context, there is a massive over reaction. We all make dumb shit, but there's no need for actual harassment.

The thing is that the least intrusive approach (dialogue box with a Close button locked until the user ticks a "I acknowledge and have read what you are telling me" tick, a-la license conditions) would also be the best UX - avoiding the entire issue in the first place, and that's not even including the general tone of the code itself.

Harassment is inappropriate but the pushback isn't.

**Comment by Spaceghost** [comment]
So it's you. No wonder you're disappearing your work. It's been archived. Along with everything you've done with this identity.

See my comment on the latent issue regarding the quality and value of your work and you as a person in this repo. I'm willing to put $1000/month to see your work eradicated from builds and only kept as an artifact to be leered at for all time in the open source and emulation communities.

You have been weighed, you have been measured, and you have been found wanting. Destroy this identity, become someone less abjectly harmful.

**Comment by foxt** [comment]
> The thing is that the least intrusive approach (dialogue box with a Close button locked until the user ticks a "I acknowledge and have read what you are telling me" tick, a-la license conditions) would also be the best UX - avoiding the entire issue in the first place, and that's not even including the general tone of the code itself.

Calling the user an idiot is very bad. But as someone who has wrote software used by 100K+ users I understand the frustration (still, be nice to your users.)

As I'm sure you're aware, there's no standard MessageBoxWithCheckboxA Windows API, and developers are generally lazy 😉.

**Comment by Spaceghost** [comment]
You've got to be like fifteen. Tell me you're just a child without any real life experience and that you're just hacking away in your bedroom and willing to admit you shouldn't have merge permissions anymore. I'm astounded at what you'll do to people to not get bothered in your cute little discord.

Bro I was around for irc, you just don't have the chops if you can't manage channels and write bots to automate text based workflows. You can't honestly believe to yourself that you're a cogent and reasonable engineer after this man. You have to be a child, I refuse to accept that you're legally responsible for yourself.

Go create a new account and be less abjectly damaging because of your little feelings about a _chat_ server. It's best to be forgotten.

**Comment by BillieBlueberry** [comment]
If chrisps code gets removed, both master and canary get a big downgrade

**Comment by CookiePLMonster** [comment]
> Calling the user an idiot is very bad. But as someone who has wrote software used by 100K+ users I understand the frustration (still, be nice to your users.)

For sure, but an ability to contain that frustration and not externalize it where everyone can see it in public is one of the things that can set professionals and hobbyists apart.

> As I'm sure you're aware, there's no standard MessageBoxWithCheckboxA Windows API, and developers are generally lazy 😉.

But that's exactly my point - is spawning an indirect dialog box ([TaskDialogIndirect](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-taskdialogindirect)) more effort than
* Spawning a "standard" message box
* Starting a timer
* Beeping (idk if just once or many times, I have not ran this code locally)
* Waiting for input
* Measuring time spent reading
* Persisting this flag **outside of the normal Xenia's config file**

I would argue the "good" approach would have been less effort.

**Comment by Spaceghost** [comment]
I need the canary team to release a statement and to contact YouTubers to get the apology out. You've harmed the real Xenia reputation. You're just a canary fork

Let Chris go away but let his work be called out as it deserves. Harmful and ignorant. A child's volatile solution to being bothered by lines of text. Until this is fully placed in the forefront with a post that will never be removed from the repo docs so all canary users get notified of your missteps and poor choices of the past, I will continue to give all emulation teams between $20-50/month of personal funding except your team. This is worse than a security vulnerability.

Edit:
Canary contributors can downvote all you want, I'll give more to other projects to spite you and do some good here lol
And because you didn't reach out to give a statement, YouTubers already published embarrassing summaries of this. Good job fumbling your apology tour

**Comment by ca-lee-b** [comment]
> 

I understand the frustration but this is a bit too much don't you think? This is a canary repository, not even the main repository. Additionally, to say this is worse than a security vulnerability is an extreme exaggeration. I think discussion on this issue should move elsewhere.

**Comment by Daisouji** [comment]
I'm surprised it got merged, imagine what else could merged w/o people knowing.

**Comment by TorutheRedFox** [comment]
> Why not just have a disclaimer show up the first time xenia is run instead of when you load an ISO? have it be a window that you can only close after a fixed amount of time has passed (maybe 10 seconds)
> 
> should filter out most pirates from seeking support in the discord or at least they will make sure to not reveal where they got the game from

have it appear the first few times xenia is ran and basically leave the user alone after that

**Comment by breezeepeezee** [comment]
i'm sorry for being a bit late to the party, but i think a better feature that would benefit a lot more people would be an iso hash check. 

personally, i find the redump website to be an incredible resource for genuine dump data, and i think xenia should cross reference redump's data so that way people know for sure their own dumps are genuine. (as opposed to punishing people who have dumped their own games legally)

**Comment by eris-webserv** [comment]
the dev that made this change deleted their Github account. I actually feel sad it went this far now

**Comment by zlago** [comment]
just a passerby but what the hell

- at times i am obsessed with keeping things clean, and i did consider converting files to `.iso` for the sake of having one convinient file (girlfriend be playing around with psx and i get sent `.bin` and `.cue`)
- not all pirate copies use `.iso`
- what even are the logistics of a "user clicked off early, assume theyre a pirate"?
    * someone could read it quickly, and be falsely flagged
    * a pirate could take their time to read the popup anyways and not get flagged

i dont even care about the antipiracy thing or the malware thing, why is this all so stupidly arbitrary? who is this targetting, pirates or nerds? and who in their right mind would do these changes disguised as a normal PR? (maybe its just me being scared of making any changes without prior approval..)

**Comment by ZiroGX2** [comment]
Baffles me too. Given one of the only ways to dump your games on an unmodded system is to use god2iso

**Comment by Illasera** [comment]
lol at OP, what a ƒaggot, KYS

**Comment by Rackhamn** [comment]
Another passerby.

Most of my old EA games (pc-rom) are just an .iso file burned to the physical disk.

Also, there is nothing wrong with using .iso, however if you really care about not letting 'pirates' use xenia again you can do a hash check, then say 'we think you are a somalian pirate' and quit the program on input.

Really neet.

**Comment by pentargency** [comment]
Wow. I see so many terrible decisions like this get made in open source projects in a futile attempt to help manage inherently unmanageable front-line Discord support communities and reconcile this new role with their original purpose of being contributor and enthusiast comms.

Why are people still using Discord as a primary support community when it inevitably ends up as such an unmanageable morass of external band-aids and user hostility to help keep it usable? It seems like a chat room is not ideal for this kind of community. This issue, really, seems to me to be primarily a sign that Xenia is managing its community and support systems incorrectly. They're certainly not alone in making this mistake, to be fair.

Back in the day, for this reason, we would have forums for user support, larger-form discussions, and documentation... and developers on chat/IRC for faster or more ephemeral discussions. Consider, perhaps, an official subreddit or Lemmy/kbin community for front-line support and reclaim the Discord for contributor/tester/enthusiast comms by de-emphasizing it? Sure a hell of a lot better than intentionally trying to spook your users by blasting sounds and treating them like imbeciles because of your chatroom moderation inadequacies.

I find it really hard to understand the mentality of having trouble managing a _Discord server_ leading to borderline-malicious user-hostile changes in the project, instead of just fixing the underlying problem of _using a chat room platform inappropriately_.

**Comment by bctnry** [comment]
> the dev that made this change deleted their Github account. I actually feel sad it went this far now

Good riddance. Man should've seen it coming from miles away...

**Comment by burty-tech** [comment]
I actually got this message loading a game the other day and it was bizarre & felt like malware. I guess I was naïve to think a project like this would be inherently "safe" to run.

**Comment by ghost** [comment]
This made me unwatch and unstar this repo. Never again on here

**Comment by xan1242** [comment]
> > the dev that made this change deleted their Github account. I actually feel sad it went this far now
> 
> Good riddance. Man should've seen it coming from miles away...

You do realize that they were a pretty active contributor up until this point? It didn't need to go this far. A slap on the wrist was warranted at most.

I'd understand if they were a repeat offender or a troll, but they were an **active developer** contributing **real improvements** to the project.

I see this more as a loss than a win for the project (and open-source as a whole, he had some good projects). Let this be a lesson for the future.

**Comment by ParasiteXX** [comment]
This has to be one of the stupidest changes anyone has ever added to any program.. Good riddance you got kicked off the Xenia team..

**Comment by ghost** [comment]
> This has to be one of the stupidest changes anyone has ever added to any program.. Good riddance you got kicked off the Xenia team..

If you were talking to me, no, I didn't contribute to Xenia or Canary, I just quit watching the repo and unstarred it.

**Comment by acanthii** [comment]
> > > the dev that made this change deleted their Github account. I actually feel sad it went this far now
> > 
> > 
> > Good riddance. Man should've seen it coming from miles away...
> 
> You do realize that they were a pretty active contributor up until this point? It didn't need to go this far. A slap on the wrist was warranted at most.
> 
> I'd understand if they were a repeat offender or a troll, but they were an **active developer** contributing **real improvements** to the project.
> 
> I see this more as a loss than a win for the project (and open-source as a whole, he had some good projects). Let this be a lesson for the future.

A lot of us didn't want the dev removed, we were simply being vocal about a change that was harmful to Xenia. It's not us, but the Xenia-Canary team that decides the punishments.

**Comment by xan1242** [comment]
This wasn't a punishment of any sorts. [It was a decision brought by chris himself.](https://github.com/xenia-canary/xenia-canary/pull/184#issuecomment-1653630882)

A lot of this being "simply vocal" is people coming from Twitter raging about this and going to directly harass him over this stupidity.

I'm not defending what he did here, it was absolutely stupid and petty. But let's just get the facts straight first and not be driven by emotion.

**Comment by nebula-neru** [comment]
jesus christ

**Comment by ddvarpdd** [comment]
>I'd understand if they were a repeat offender or a troll, but they were an active developer contributing real improvements to the project.

Play stupid games, win stupid prizes. The author was willing to compromise the project over his grievances with mean end-users. Keeping him as an active maintainer is a liability regardless of quality of his past contributions.

**Comment by IruzzArcana** [comment]
> the dev that made this change deleted their Github account.

Good.

**Comment by 0x3C50** [comment]
> the dev that made this change deleted their Github account. I actually feel sad it went this far now

don't feel sad, if a contributor decides to merge an almost malware-like piece of code into an open source project without discussing or even thinking about it, they absolutely deserve to be flamed for it. them being gone now benefits everyone else, but i know the idiot is still around somewhere. if you, the author of this pr, read this: everything that happened was deserved, and i do not feel bad about it in the slightest. go harass another open source project

**Comment by xan1242** [comment]
> Keeping him as an active maintainer is a liability regardless of quality of his past contributions.

I beg to differ.

He's a human being (right?). He deserves a second chance. You don't oust someone right away, even over a thing like this. This, while it is petty malicious code, it is just that. He didn't murder the project. He was just dumb enough to think it would go through.

What you do, after absolutely flaming them for their stupidity, is _talk_ to them. Try to come to a resolution, try to correct their actions and then determine what to do next. This is exactly what should've happened not a day later after the first comment to this PR, but it didn't.

None of us know anything about exactly what transpired behind the scenes. But, from what I can tell from the outside - this being merged in the code for the whole 4 days before it was removed tells that this was mismanaged from everyone involved. Yes, this includes other team members and/or contributors who should've reacted. None of this would've happened if it was caught in time and talked through.

It's a "fool me once, fool me twice" situation. You can't base your judgment on one stupid move after many good ones.

If it comes down to his decision of being frustrated and leaving, then so be it, but let it be just that and nothing more.

**Pull request merged**
