### PR TITLE
Superbig boost in performance?

### PR DESCRIPTION
**Pull request by ghost**
Huge set of performance improvements,  users have reported absurd gains over master for some gains, in the range 30%-90%

Added per-xexmodule caching of information per instruction, can be used to remember what code needs compiling at start up
Record what guest addresses wrote mmio and backpropagate that to future runs, eliminating dependence on exception trapping. this makes many games like h3 actually tolerable to run under a debugger
fixed a number of errors where temporaries were being passed by reference/pointer
Can now be compiled with clang-cl 14.0.1, requires -Werror off though and some other solution/project changes.
Added macros wrapping compiler extensions like noinline, forceinline, __expect, and cold.
Removed the "global lock" in guest code completely. It does not properly emulate the behavior of mfmsrd/mtmsr and it seriously cripples amd cpus. Removing this yielded around a 3x speedup in Halo Reach for me.
Disabled the microprofiler for now. The microprofiler has a huge performance cost associated with it. Developers can re-enable it in the base/profiling header if they really need it
Disable the trace writer in release builds. despite just returning after checking if the file was open the trace functions were consuming about 0.60% cpu time total
Add IsValidReg, GetRegisterInfo is a huge (about 45k) branching function and using that to check if a register was valid consumed a significant chunk of time
Optimized RingBuffer::ReadAndSwap and RingBuffer::read_count. This gave us the largest overall boost in performance. The memcpies were unnecessary and one of them was always a no-op
Added simplification rules for multiplicative patterns like (x+x), (x<<1)+x
For the most frequently called win32 functions i added code to call their underlying NT implementations, which lets us skip a lot of MS code we don't care about/isnt relevant to our usecases
^this can be toggled off in the platform_win header
handle indirect call true with constant function pointer, was occurring in h3
lookup host format swizzle in denser array
by default, don't check if a gpu register is unknown, instead just check if its out of range. controlled by a cvar
^looking up whether its known or not took approx 0.3% cpu time
Changed some things in /cpu to make the project UNITYBUILD friendly
The timer thread was spinning way too much and consuming a ton of cpu, changed it to use a blocking wait instead
tagged some conditions as XE_UNLIKELY/LIKELY based on profiler feedback (will only affect clang builds)
Shifted around some code in CommandProcessor::WriteRegister based on how frequently it was executed
added support for docdecaduple precision floating point so that we can represent our performance gains numerically
tons of other stuff im probably forgetting

### CODE REVIEW

**Comment by Blackbird88** [comment]
Great job!
Before
image
After (vsync_interval = 8)
image

**Comment by t0mtee** [comment]
this is insane, rdr is so good now, especially with 1080p through 540p patch and 2x res scale.

**Comment by ajax-lives** [comment]
Its people like you who inspire me to change my major back to software development.  Fantastic work, absolutely incredible.
#
Tested with Red Dead Redemption on a midspec PC and am pushing past 60 FPS with relative ease.

**Comment by ajax-lives** [comment]
Tested with Red Dead Redemption on a midspec PC and am pushing past 60 FPS with relative ease.

**Comment by Epsilon160** [comment]
Hello all,

I don't know if this is the best place to explain the problem and share it with competent people but I've been trying since this morning to get golden eye 007 xbla to work with xenia master but without much success. With xenia master, my fps are very very low but on the other hand I manage to use the mouse and the keyboard thanks to the mousehook V1.13.4 patch. Which works pretty well but doesn't fix my framerate issue. After some research I discovered the latest version of xenia canary and there it is day and night. I go from 20-30 fps to 60 fps stable .... All happy I search so I even fix for the keyboard and the mouse but for the latest version of xenia canary (https://github.com/xenia-canary/ xenia-canary/releases) and there unfortunately it gets stuck. I find a version of the mousehook for xenia canary via redit (by Marcelo20XX). But there it gets stuck, when I replace the program I find myself with again 20-30 fps in games... I specify my config, rtx 3090 and ryzen 5950x. Thank you in advance for the help and for all the work done by independent modders and devs to bring this masterpiece back to life on pc =)

**Comment by Margen67** [comment]
@Epsilon93 Ask for tech support on the Xenia Discord server, not here: https://discord.gg/Q9mxZf9

**Comment by Epsilon160** [comment]
Ok thank you for the way ;)

**Pull request merged**
