### PR TITLE
Readme: Update readme branding + download url

### PR DESCRIPTION
**Pull request by illusionyy**
Release page is silly. We should replace the icon with a better less artifacts one.

### CODE REVIEW

**Comment by Margen67** [comment]
The icons have been replaced with less crusty ones: #190

**Comment by illusionyy** [comment]
Fixed

**Comment by Margen67** [comment]
The issue template should also be fixed.

**Comment by illusionyy** [comment]
Where

**Comment by Margen67** [comment]
> Where

https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/.github/ISSUE_TEMPLATE/bug_report.yaml

**Comment by Margen67** [comment]
https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/.github/ISSUE_TEMPLATE/config.yml

**Comment by illusionyy** [comment]
> https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/.github/ISSUE_TEMPLATE/config.yml

We don't have a discord server though.

**Comment by illusionyy** [comment]
> > Where
> 
> https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/.github/ISSUE_TEMPLATE/bug_report.yaml

What's there to be fixed? It's outside the scope of this pr

**Comment by Margen67** [comment]
> > > Where
> > 
> > 
> > [`canary_experimental`/.github/ISSUE_TEMPLATE/bug_report.yaml](https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/.github/ISSUE_TEMPLATE/bug_report.yaml?rgh-link-date=2023-07-29T17%3A21%3A06Z)
> 
> What's there to be fixed? It's outside the scope of this pr

It should say issue is from Canary, not master.
Should I make a new PR to fix it?

**Comment by illusionyy** [comment]
> > > > Where
> > > 
> > > 
> > > [`canary_experimental`/.github/ISSUE_TEMPLATE/bug_report.yaml](https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/.github/ISSUE_TEMPLATE/bug_report.yaml?rgh-link-date=2023-07-29T17%3A21%3A06Z)
> > 
> > 
> > What's there to be fixed? It's outside the scope of this pr
> 
> It should say issue is from Canary, not master. Should I make a new PR to fix it?

Yes

**Comment by LocoabordoR8** [comment]
illusion0001:Readme

**Comment by Margen67** [comment]
@LocoabordoR8 Nothing you say makes sense. Give me a good reason not to block you.

**Pull request closed without merging**
