### PR TITLE
fix Linux build

### PR DESCRIPTION
**Pull request by q4a**
Basic fix Linux build.
app/check_update.cc - is not ported to Linux yet.
kernel/xam/xam_user.cc - one assert temporary disabled for Linux:
`static_assert_size(X_PROFILEENUMRESULT, 0x188);`

Here is my build result:
https://travis-ci.org/q4a/xenia/builds/657121748

### CODE REVIEW

**Comment by q4a** [comment]
Sorry, it's WIP. Looks like I have some regressions (

**Comment by randprint** [comment]
Thanks I guess but we told you when you queried in discord about this that your PR should be based on the master branch and submitted there, following the progress of the work other people are doing in linux there.

**Comment by q4a** [comment]
I did additional checks. Looks like all fine.

**Comment by randprint** [comment]
not all fine, this is canary, not master.

**Comment by emoose** [comment]
The changes here are good, had no idea I was breaking so many Linux things, but I can see why we wouldn't want to accept PRs to the main canary branch: really it's messy enough as it is with all the random fixes/non-PRed stuff being there...

Ideally I _think_ we should have all the non-PR'd changes in separate branches (based on master), and then you could PR your fixes into those branches (and then eventually maybe we could PR those branches to master), but like I said it's all a bit messy right now..

There's a few things in branches but I think they might be missing extra things which were only pushed to the main canary branch (and also those branches are based on canary instead of master, so we can't really PR those into master, if anyone's wondering why I haven't PR'd any of the big things over to master lately...)
I'm not really sure what the best way to solve this is yet though, but I'm all ears if anyone has any suggestions.

**Comment by randprint** [comment]
in almost all cases, except for instance when you rebased some of your work on canary for ease of merging. Or in the cases we're trying experimental things and want to get some user feedback on a wider variety of games/machines before making choices

**Comment by randprint** [comment]
as we've progressed we've dropped those 'random' commits or made PRs of the experimental things after testing proved them to be good to keep or scrap. Leaving the experimental things out of PRs also has kept them from spilling over into unofficial builds where they just scrape up everything without knowing about it.

**Pull request closed without merging**
