### PR TITLE
Third-party: Update a lot of submodules

### PR DESCRIPTION
**Pull request by Xphalnos**
I have updated a lot of dependencies like:

| Library | Old version | New version |
| -------- | -------- | -------- |
| Vulkan-Headers | v1.3.280 | v1.3.295 |
| imgui | v1.89.0 | v1.89.5  |
| Xbyak | v7.05.1 | v7.07.1 |
| SPIRV-Tools | v2023.2 | v2024.3 |
| Vulkan Memory Allocator | v3.0.1 | 3.1.0 |
| Capstone | v3.0.3 | v5.0.3 |
| Catch2 | v2.10.2 | v3.7.0 |
| zstd | v1.5.5 | v1.5.6 |
| stb_image.h | v2.08 | v2.30 |
| stb_image_write.h | v1.00 | v1.16 |

Note:
- For imgui, I was able to update to 1.89.5 because above, I could not fix the compilation errors
- In Workflows I updated Windows-2019 to Windows-2022 as it doesn't seem to cause any issues
- I haven't updated fmt and SDL2 because they are causing a lot of issues. If I can fix them I'll make another commit.

### CODE REVIEW

**Comment by Gliniak** [comment]
Hi,

About that windows workflow version. We were using 2022 version, but there was an issue with a lot of false-positives for whatever reason and I see it still does that. Plus there were multiple reports with crashing on boot due to some incompatibility between different SDK or something and users redist version

**Comment by Xphalnos** [comment]
> Hi,
> 
> About that windows workflow version. We were using 2022 version, but there was an issue with a lot of false-positives for whatever reason and I see it still does that. Plus there were multiple reports with crashing on boot due to some incompatibility between different SDK or something and users redist version

You mean I have to put Windows-2019 back?

**Comment by Gliniak** [comment]
> > Hi,
> > About that windows workflow version. We were using 2022 version, but there was an issue with a lot of false-positives for whatever reason and I see it still does that. Plus there were multiple reports with crashing on boot due to some incompatibility between different SDK or something and users redist version
> 
> You mean I have to put Windows-2019 back?

Yes, please

**Comment by Xphalnos** [comment]
It's back!

**Comment by Xphalnos** [comment]
Windows-2019 is back!

**Comment by Gliniak** [comment]
Ok, can you just change this PR into one commit, because last 2 commits cancel each other out. Thanks.

I will let it sit there for a few days, so community and I can check if everything is as stable as it was since you're changing version of Xbyak and Capstone

**Comment by Xphalnos** [comment]
OK I'm reopening another commit

**Comment by Gliniak** [comment]
But why? You could just use command: ``git rebase --interactive HEAD~3`` and select that you want to drop last two commits and then force-push to your branch

**Comment by Xphalnos** [comment]
> But why? You could just use command: `git rebase --interactive HEAD~3` and select that you want to drop last two commits and then force-push to your branch

Excuse me, I am really sorry for the inconvenience.

**Pull request closed without merging**
